version: "3.8"
name: k4os-orleans

services: 
  storage:
    image: redis:7.2.1
    command: "--appendonly yes"
    ports:
      - "6379:6379"
    volumes:
      - ./../.local/storage/data:/data
  
  envoy:
    image: envoyproxy/envoy:distroless-v1.27-latest
    ports:
      - "9998:9998"
      - "9999:9999"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      
  silo:
    image: k4os-template-orleans-silo:latest
    depends_on:
      - storage
    deploy:
      replicas: 3
    environment:
      - "Silo__Cluster__RedisEndpoint=redis://storage:6379"
      - "Silo__Persistence__RedisEndpoint=redis://storage:6379"
      - "Silo__Reminders__RedisEndpoint=redis://storage:6379"

  api:
    image: k4os-template-orleans-api:latest
    depends_on:
      - silo
    environment:
      - "Silo__Cluster__RedisEndpoint=redis://storage:6379"
        
  dashboard:
    image: k4os-template-orleans-dashboard:latest
    depends_on:
      - silo
    environment:
      - "Silo__Cluster__RedisEndpoint=redis://storage:6379"
